import "../style/globals.css";
import "../style/font.css";

import "aos/dist/aos.css";
import "animate.css";

import "keen-slider/keen-slider.min.css";

import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import { ThemeProvider } from "next-themes";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "کافه عربیکا - صفحه اصلی",
  description: "Generated by create next app",
  icons: {
    icon: "@/public/image/fav-icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" enableSystem>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
