import "../style/globals.css";
import "../style/font.css";

import "aos/dist/aos.css";
import AOS from "aos";
import "animate.css";

import "keen-slider/keen-slider.min.css";

import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "@/public/image/fav-icon.png",
  },
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
