import "../style/globals.css";
import "../style/font.css";

import "aos/dist/aos.css";
import "animate.css";

import "keen-slider/keen-slider.min.css";

import { ThemeProvider } from "next-themes";

import Header from "../components/header/Header";
import Footer from "../components/footer/Footer";
import ProviderRedux from "../redux/providerRedux";
import { ReactNode } from "react";

// import localFont from "next/font/local";
// const myFont = localFont({
//   src: [
//     {
//       path: "../public/fonts/Dana/woff2/DanaFaNum-Regular.woff2",
//       weight: "400",
//       style: "normal",
//     },
//     {
//       path: "../public/fonts/Dana/woff2/DanaFaNum-Medium.woff2",
//       weight: "500",
//       style: "normal",
//     },
//     {
//       path: "../public/fonts/Dana/woff2/DanaFaNum-DemiBold.woff2",
//       weight: "600",
//       style: "normal",
//     },
//   ],
// });

// const Dana = localFont({
//   src: [
//     {
//       path: "../public/fonts/Dana/woff2/DanaFaNum-Regular.woff2",
//       weight: "400",
//       style: "normal",
//     },
//     {
//       path: "../public/fonts/Dana/woff2/DanaFaNum-Medium.woff2",
//       weight: "500",
//       style: "normal",
//     },
//     {
//       path: "../public/fonts/Dana/woff2/DanaFaNum-DemiBold.woff2",
//       weight: "600",
//       style: "normal",
//     },
//   ],
// });

// const Morabba = localFont({
//   src: [
//     {
//       path: "../public/fonts/Morabba/woff2/Morabba-Light.woff2",
//       weight: "300",
//       style: "normal",
//     },
//     {
//       path: "../public/fonts/Morabba/woff2/Morabba-Medium.woff2",
//       weight: "500",
//       style: "normal",
//     },
//     {
//       path: "../public/fonts/Morabba/woff2/Morabba-Bold.woff2",
//       weight: "900",
//       style: "normal",
//     },
//   ],
// });

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "کافه عربیکا - صفحه اصلی",
  description: "Generated by create next app",
  icons: {
    icon: "@/public/image/fav-icon.png",
  },
};

export default function RootLayout({ children }: { children : ReactNode}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" enableSystem>
          <ProviderRedux>
            <Header />
            {children}
            <Footer />
          </ProviderRedux>
        </ThemeProvider>
      </body>
    </html>
  );
}
